kind: pipeline
name: static-tests

steps:
- name: flake8
  image: alpine/flake8:3.7.9
  commands:
  - flake8

# fails on local development
#- name: leaks
#  image: zricethezav/gitleaks:v6.2.0
#

---
kind: pipeline
name: integration-tests

depends_on:
- static-tests

node:
  connect_target_ssh: true

steps:
- name: copy code to target
  image: appleboy/drone-scp:latest
  settings:
    host:
      from_secret: target_hostname
    username:
      from_secret: target_username
    password:
      from_secret: target_password
    port:
      from_secret: target_port
    source: .
    target: /app-test/code
    rm: true


- name: run tests on target
  image: appleboy/drone-ssh:latest
  settings:
    host:
      from_secret: target_hostname
    username:
      from_secret: target_username
    password:
      from_secret: target_password
    port:
      from_secret: target_port
    command_timeout: 60m
    script:
      - cd /app-test/code
      - ./ci/run-integration-tests.sh

---
kind: secret
name: target_username
get:
  path: liquid/ci/drone.target
  name: username

---
kind: secret
name: target_password
get:
  path: liquid/ci/drone.target
  name: password

---
kind: secret
name: target_hostname
get:
  path: liquid/ci/drone.target
  name: hostname

---
kind: secret
name: target_port
get:
  path: liquid/ci/drone.target
  name: port
